source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target "FMBaseOCProject" do
    pod 'RETableViewManager'    
end
target "ShuiDongGou" do
    pod 'RETableViewManager'
    pod 'Toast', '~> 3.1.0'
    pod 'AFNetworking'
    pod 'SDWebImage'
    pod 'MBProgressHUD'
    pod 'MJRefresh'
end

